server:
  port: 8080

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      port: 27017
      database: StudentReward
      authentication-database: admin
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka # http://uname:pword@docker_name:port/eureka

grpc:
  server:
    port: 0
  client:
    grpc-household:
      address: pse-household-service
      negotiation-type: plaintext