server:
  port: 0

spring:
  data:
    mongodb:
      host: mongo
      username: root
      password: example
      port: 27017
      database: StudentReward
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # http://uname:pword@docker_name:port/eureka

grpc:
  server:
    port: 0
  client:
    grpc-household:
      address: pse-household-service
      negotiation-type: plaintext