version: '3'

services:
  mongo-service:
    container_name: tths-database-mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TTHS_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TTHS_MONGO_PASSWORD}
    volumes:
      - ./data-example/mongodb-data:/data/db
  discovery-server:
    build: discovery-server
    image: tths-microservice-discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - 8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  api-gateway:
    build: api-gateway
    image: tths-microservice-api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
      - MONGO_HOST=${TTHS_MONGO_HOST}
      - MONGO_USERNAME=${TTHS_MONGO_USERNAME}
      - MONGO_PASSWORD=${TTHS_MONGO_PASSWORD}
    depends_on:
      - discovery-server
  accountant-service:
    build: accountant-service
    image: tths-microservice-accountant-service
    container_name: accountant-service
    links:
      - mongo-service:${TTHS_MONGO_HOST}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - MONGO_HOST=${TTHS_MONGO_HOST}
      - MONGO_USERNAME=${TTHS_MONGO_USERNAME}
      - MONGO_PASSWORD=${TTHS_MONGO_PASSWORD}
    depends_on:
      - mongo-service
      - discovery-server
      - api-gateway
  auth-service:
    build: auth-service
    image: tths-microservice-auth-service
    container_name: auth-service
    links:
      - mongo-service:${TTHS_MONGO_HOST}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=${TTHS_MONGO_HOST}
      - MONGO_USERNAME=${TTHS_MONGO_USERNAME}
      - MONGO_PASSWORD=${TTHS_MONGO_PASSWORD}
    depends_on:
      - mongo-service
      - discovery-server
      - api-gateway
  household-service:
    build: household-service
    image: tths-microservice-household-service
    container_name: household-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
  statistic-service:
    build: statistic-service
    image: tths-microservice-statistic-service
    container_name: statistic-service
    links:
      - mongo-service:${TTHS_MONGO_HOST}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=${TTHS_MONGO_HOST}
      - MONGO_USERNAME=${TTHS_MONGO_USERNAME}
      - MONGO_PASSWORD=${TTHS_MONGO_PASSWORD}
    depends_on:
      - mongo-service
      - discovery-server
      - api-gateway
  student-service:
    build: student-service
    image: tths-microservice-student-service
    container_name: student-service
    links:
      - mongo-service:${TTHS_MONGO_HOST}
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=${TTHS_MONGO_HOST}
      - MONGO_USERNAME=${TTHS_MONGO_USERNAME}
      - MONGO_PASSWORD=${TTHS_MONGO_PASSWORD}
    depends_on:
      - mongo-service
      - discovery-server
      - api-gateway
