server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka # http://uname:pword@docker_name:port/eureka

spring:
  data:
    mongodb:
      host: localhost
      username: root
      password: example
      port: 27017
      database: StudentReward