server:
  port: 0

spring:
  application:
    name: student-service
  data:
    mongodb:
      uri: mongodb://user2:password2@localhost:27017/?authMechanism=SCRAM-SHA-1
      database: StudentReward

  testdata:
    student:
      householdnumber: 16894576

  app:
    jwtCookieName: tths
    jwtSecret: tths_private
    jwtExpirationMs: 86400000

gui:
  uri: http://localhost:4200, http://localhost:4201

logging:
  rootCategory: INFO, consoleAppender, fileAppender

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 0

  client:
    auth-service:
      address: auth-service
      negotiation-type: plaintext
