server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka # http://uname:pword@docker_name:port/eureka

spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      port: 27017
      database: StudentReward
      authentication-database: admin
  application:
    name: student-service