server:
  port: 0

spring:
  application:
    name: statistic-service
  data:
    mongodb:
      uri: mongodb+srv://java:java@tths.np7ff7c.mongodb.net/?retryWrites=true&w=majority
      database: StudentReward

  testdata:
    student:
      householdnumber: 16894576

  app:
    jwtCookieName: tths
    jwtSecret: tths_private
    jwtExpirationMs: 86400000

gui:
  uri: http://localhost:4200, http://localhost:4201

logging:
  rootCategory: INFO, consoleAppender, fileAppender

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
  client:
    grpc-student-service:
      address: lb:student-service
      negotiation-type: plaintext # ssl must be mentioned here if used
    grpc-reward-detail-service:
      address: lb:accountant-service
      negotiation-type: plaintext
    grpc-prize-period-service:
      address: lb:accountant-service
      negotiation-type: plaintext
    grpc-auth-service:
      address: lb:auth-service
      negotiation-type: plaintext