server:
  port: 0

spring:
  application:
    name: accountant-service
  data:
    mongodb:
      uri: mongodb+srv://java:java@tths.np7ff7c.mongodb.net/?retryWrites=true&w=majority
      database: StudentReward

  testdata:
    student:
      householdnumber: 16894576

  app:
    jwtCookieName: tths
    jwtSecret: tths_private
    jwtExpirationMs: 86400000


logging:
  rootCategory: INFO, consoleAppender, fileAppender
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 0

  client:
    auth-service:
      address: lb:auth-service
      negotiation-type: plaintext
