server:
  port: 0

spring:
  application:
    name: accountant-service
  data:
    mongodb:
      host: localhost
      username: root
      password: example
      port: 27017
      database: StudentReward
      authentication-database: admin

  testdata:
    student:
      householdnumber: 16894576

  app:
    jwtCookieName: tths
    jwtSecret: tths_private
    jwtExpirationMs: 86400000


logging:
  rootCategory: INFO, consoleAppender, fileAppender
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 0

  client:
    auth-service:
      address: AUTH-SERVICE
      negotiation-type: plaintext
