server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka # http://uname:pword@docker_name:port/eureka

spring:
  application:
    name: accountant-service
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/?authMechanism=SCRAM-SHA-256
      database: StudentReward